version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=autoria
      - POSTGRES_USER=autoria_user
      - POSTGRES_PASSWORD=autoria_pass
      - SCRAPING_TIME=12:00
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: autoria
      POSTGRES_USER: autoria_user
      POSTGRES_PASSWORD: autoria_pass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: