version: '3.8'

services:
  db:
    image: postgres:15
    container_name: autoria_db
    environment:
      - POSTGRES_DB=autoria
      - POSTGRES_USER=autoria_user
      - POSTGRES_PASSWORD=autoria_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - autoria_network

networks:
  autoria_network:
    driver: bridge

volumes:
  db_data: